# Setup
title:               Jasim's Blog
tagline:             'Blog about Passion'
description:         'Made by Ahamed'
url:                 https://jasim2k.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Jasim
  url:               https://jasim2k.github.io
  email:             abc@yahoo.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0